# Generated by Django 3.2.20 on 2023-08-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
