# Generated by Django 3.2.20 on 2023-08-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='task_id',
            field=models.IntegerField(unique=True),
        ),
    ]
